[2023-03-27T20:34:10.891+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_to_neo4j manual__2023-03-27T20:34:06.935704+00:00 [queued]>
[2023-03-27T20:34:10.903+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_to_neo4j manual__2023-03-27T20:34:06.935704+00:00 [queued]>
[2023-03-27T20:34:10.904+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T20:34:10.906+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-27T20:34:10.907+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T20:34:10.921+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_to_neo4j> on 2023-03-27 20:34:06.935704+00:00
[2023-03-27T20:34:10.927+0000] {standard_task_runner.py:55} INFO - Started process 2614 to run task
[2023-03-27T20:34:10.930+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_to_neo4j', 'manual__2023-03-27T20:34:06.935704+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmpdewrn8wl']
[2023-03-27T20:34:10.931+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask write_to_neo4j
[2023-03-27T20:34:11.030+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_to_neo4j manual__2023-03-27T20:34:06.935704+00:00 [running]> on host 55adc3415b92
[2023-03-27T20:34:11.122+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_to_neo4j
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T20:34:06.935704+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T20:34:06.935704+00:00
[2023-03-27T20:34:11.125+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 48, in write_to_neo4j
    parsed_data = parse_data(dict_data, accession)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 60, in parse_data
    parsed_data.extend(parse_references(dict_data))
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 117, in parse_references
    "id": citation["@id"],
KeyError: '@id'
[2023-03-27T20:34:11.150+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_to_neo4j, execution_date=20230327T203406, start_date=20230327T203410, end_date=20230327T203411
[2023-03-27T20:34:11.171+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task write_to_neo4j ('@id'; 2614)
[2023-03-27T20:34:11.185+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-27T20:34:11.217+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
