[2023-03-28T21:41:10.880+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_authors_of_references manual__2023-03-28T21:41:00.970517+00:00 [queued]>
[2023-03-28T21:41:10.898+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_authors_of_references manual__2023-03-28T21:41:00.970517+00:00 [queued]>
[2023-03-28T21:41:10.899+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T21:41:10.900+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T21:41:10.901+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T21:41:10.928+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_authors_of_references> on 2023-03-28 21:41:00.970517+00:00
[2023-03-28T21:41:10.936+0000] {standard_task_runner.py:55} INFO - Started process 19511 to run task
[2023-03-28T21:41:10.941+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_authors_of_references', 'manual__2023-03-28T21:41:00.970517+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmp2uaoyqmt']
[2023-03-28T21:41:10.942+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask write_authors_of_references
[2023-03-28T21:41:11.051+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_authors_of_references manual__2023-03-28T21:41:00.970517+00:00 [running]> on host 8482e168b99d
[2023-03-28T21:41:11.203+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_authors_of_references
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T21:41:00.970517+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T21:41:00.970517+00:00
[2023-03-28T21:41:11.206+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 455, in write_authors_of_references
    if not author_list:
NameError: name 'author_list' is not defined
[2023-03-28T21:41:11.247+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_authors_of_references, execution_date=20230328T214100, start_date=20230328T214110, end_date=20230328T214111
[2023-03-28T21:41:11.278+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 138 for task write_authors_of_references (name 'author_list' is not defined; 19511)
[2023-03-28T21:41:11.317+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T21:41:11.366+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
